name: lean_requester
description: "A new Flutter package project."
version: 0.0.1
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/connectivity_plus/connectivity_plus
issue_tracker: https://github.com/fluttercommunity/plus_plugins/labels/connectivity_plus
publish_to: none

environment:
  sdk: ">=3.6.1"
  flutter: ">=3.27.2"

dependencies:
  flutter:
    sdk: flutter

  cg_core_defs:
    path: ../cg_core_defs

  dio:
  equatable:
  awesome_dio_interceptor:
  shared_preferences: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail:
  flutter_lints:

flutter:
