name: lean_requester
description: "A new Flutter package project."
version: 0.0.1
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/connectivity_plus/connectivity_plus
issue_tracker: https://github.com/fluttercommunity/plus_plugins/labels/connectivity_plus
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.2"

dependencies:
  flutter:
    sdk: flutter

  cg_core_defs:
    git:
      url: https://github.com/Jewelch/cg_core_defs
      ref: v1.1

  dio: ^5.8.0+1
  awesome_dio_interceptor: ^1.3.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail:
  flutter_lints: ^6.0.0

